api_token_env: CROWDIN_PERSONAL_TOKEN
project_id_env: CROWDIN_PROJECT_ID
base_path: ./redbot/
preserve_hierarchy: true
files:
  - source: cogs/**/messages.pot
    translation: /%original_path%/%locale%.po
  - source: core/**/messages.pot
    translation: /%original_path%/%locale%.po
