version: 2.1
orbs:
  crowdin: jack1142/crowdin-orb@dev:9b3c29f
jobs:
  crowdin_upload:
    executor: crowdin/crowdin-cli
    steps:
      - crowdin/prepare-env:
          github_username: jack1142
          github_token: GITHUB_TOKEN
          base_branch: zzz_circleci_crowdin
          git_name: CircleCI
          git_email: sayhi@circleci.com
      - run:
          command: |-
            apk add python3 py3-pip make
            pip3 install redgettext==3.1
            make gettext
      - crowdin/crowdin-upload-sources
      - crowdin/crowdin-upload-translations:
          language: fr
          auto_approve_imported: true
          import_eq_suggestions: true
workflows:
  crowdin:
    jobs:
#       - crowdin_upload:
#           context:
#             - crowdin-red
      - crowdin/download:
          context:
            - crowdin-red
          language: fr
          # PR options
          github_username: jack1142
          github_token: GITHUB_TOKEN
          base_branch: zzz_circleci_crowdin
          pr_branch: automated2/i18n
          commit_message: Crowdin translations downstream
          pr_title: Crowdin translations downstream
          git_name: CircleCI
          git_email: sayhi@circleci.com
